@extends('layouts.header')
@section('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css">
@endsection
@section('content')
<form  onsubmit="show();"   enctype="multipart/form-data">
    <div class='row mb-4'>
        <div class="col-md-2">
            <label class="form-label">Location</label>
            <select name="location" class="form-control" onchange="this.form.submit()">
                <option value="">Select Location</option>
                @foreach($locations as $key => $location)
                    <option value="{{ $location->id }}" @if($selectedLocation == $location->id) selected  @endif>
                        {{ $location->name }}
                    </option>
                @endforeach
            </select>
        </div>
        <div class="col-md-2">
            <label class="form-label">Date From</label>
            <input type='date' name='date_from' class='form-control' value='{{$date_from}}'   required>
        </div>
        <div class="col-md-2">
            <label class="form-label">Date To</label>
            <input type='date' name='date_to' class='form-control' value='{{$date_to}}' required>
        </div>
        <div class='col-xl-2'>
            <br>
                <button type="submit" class="btn btn-success" >
                <i class="ri-search-fill me-1"></i> Search
                </button>
        </div>
    </div>
</form>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Sales Report ({{date('M d, Y',strtotime($date_from))}} - {{date('M d, Y',strtotime($date_to))}})</h5>
                    </div>
                    <div class="card-body">
                         <table id="" class=" table table-bordered " >
                            <thead>
                                <tr>
                                    <td colspan=4 class='text-center'>
                                       <img class="" src="{{asset('images/logo_mo.png')}}" width='400px' alt="Header Avatar">
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan=4 class='text-center'>
                                        Sales Report
                                    </td>
                                </tr>
                                 <tr>
                                    <td > Date: </td>
                                    <td>({{date('M d, Y',strtotime($date_from))}} - {{date('M d, Y',strtotime($date_to))}})</td>
                                    <td > Location: </td>
                                    <td>
                                        @php
                                            $sele = $locations->where('id',$selectedLocation)->first();
                                        @endphp
                                        @if($sele)
                                        {{$sele->name}}
                                    @endif
                                </td>
                                </tr>
                                <tr>
                                    <td > Generated by: </td>
                                    <td>{{auth()->user()->name}}</td>
                                    <td >  </td>
                                    <td>
                                        
                                </td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td > Sales</td>
                                    <td  class='text-success'>  <b>{{number_format($transactions->where('product_id',null)->sum('amount_paid'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                                <tr>
                                    <td > Product</td>
                                    <td  class='text-success'>  <b>{{number_format($transactions->where('product_id','!=',null)->sum('amount_paid'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                                <tr>
                                    <td > Total</td>
                                    <td  class='text-success'>  <b>{{number_format($transactions->where('product_id','!=',null)->sum('amount_paid')+$transactions->where('product_id',null)->sum('amount_paid'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                                <tr>
                                    <td > Gcash</td>
                                    <td class='text-danger'> <b>{{number_format($transactions->where('type','gcash')->sum('amount_paid'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                                <tr>
                                    <td > HMO</td>
                                    <td class='text-danger'> <b>{{number_format($transactions->where('type','HMO')->sum('amount_paid'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                                <tr>
                                    <td > Debit</td>
                                    <td class='text-danger'> <b>{{number_format($transactions->where('type','Debit')->sum('amount_paid'),2)}}</b></td>
                                    <td colspan='2'></td>
                                    
                                </tr>
                                <tr>
                                    <td > CC</td>
                                    <td class='text-danger'> <b>{{number_format($transactions->where('type','CC')->sum('amount_paid'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                                <tr>
                                    <td > Others</td>
                                    <td class='text-danger'> <b>{{number_format($transactions->where('type','Others')->sum('amount_paid'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                                @foreach($expenses as $expense)
                                 <tr>
                                    <td > {{$expense->name}}</td>
                                    <td class='text-danger'> <b>{{number_format($expenses->sum('amount'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                                @endforeach
                                <tr>
                                    <td > Cash On Hand</td>
                                    <td > <b>{{number_format($transactions->where('type','cash')->sum('amount_paid')-$expenses->sum('amount'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                            </tbody>
                         </table>
                        <table id="" class=" table table-bordered dt-responsive nowrap table-striped align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th colspan='11' class='text-center'><b>Treatment</b></th>
                                </tr>
                                <tr>
                                    <th >#Id</th>
                                    <th >Client</th>
                                    <th >Dentist</th>
                                    <th >Dentist 2</th>
                                    <th >Dentist 3</th>
                                    <th>Type</th>
                                    <th>Remarks</th>
                                    <th>Location</th>
                                    <th>Encoded by</th>
                                    <th >Treatment</th>
                                    <th >Total Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($transactions->sortByDesc('id')->where('product_id',null) as $transaction)
                                <tr>
                                    
                                    <td>#{{$transaction->id}}</td>
                                    <td>{{$transaction->client->last_name}}, {{$transaction->client->first_name}}</td>
                                    <td>{{$transaction->dentist}}</td>
                                    <td>{{$transaction->dentist_2}}</td>
                                    <td>{{$transaction->dentist_3}}</td>
                                    <td>{{$transaction->type}}</td>
                                    <td>{{$transaction->remarks}}</td>
                                    <td>{{$transaction->location->name}}</td>
                                    <td>{{$transaction->user->name}}</td>
                                    
                                    <td>{{$transaction->treatment}}</td>
                                    <td>{{number_format($transaction->amount_paid,2)}}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <table id="" class=" table table-bordered dt-responsive nowrap table-striped align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th colspan='12' class='text-center'><b>Product</b></th>
                                </tr>
                                <tr>
                                    <th >#Id</th>
                                    <th >Client</th>
                                    <th >Dentist</th>
                                    <th >Dentist 2</th>
                                    <th >Dentist 3</th>
                                    <th>Type</th>
                                    <th>Remarks</th>
                                    <th>Location</th>
                                    <th>Encoded by</th>
                                    
                                    <th >Product</th>
                                    <th >Qty</th>
                                    <th >Total Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                @foreach($transactions->sortByDesc('id')->where('product_id','!=',null) as $transaction)
                                <tr>
                                    
                                    <td>#{{$transaction->id}}</td>
                                    <td>{{$transaction->client->last_name}}, {{$transaction->client->first_name}}</td>
                                    <td>{{$transaction->dentist}}</td>
                                    <td>{{$transaction->dentist_2}}</td>
                                    <td>{{$transaction->dentist_3}}</td>
                                    <td>{{$transaction->type}}</td>
                                    <td>{{$transaction->remarks}}</td>
                                    <td>{{$transaction->location->name}}</td>
                                    <td>{{$transaction->user->name}}</td>
                                    
                                    <td>{{$transaction->product->product_name}}</td>
                                    <td>{{$transaction->qty}}</td>
                                    <td>{{number_format($transaction->amount_paid,2)}}</td>
                                </tr>
                                @endforeach
                                
                                
                            </tbody>
                        </table>
                          <table class="table table-bordered dt-responsive nowrap table-striped align-middle" style="width:100%">
                    <thead>
                         <tr>
                            <th colspan=8 class='text-center'>Expenses</th>
                         </tr>
                         </tr>
                        <tr>
                            <th>Expense Name</th>
                            <th>Reference #</th>
                            <th>Date</th>
                            <th>Amount</th>
                            <th>Attachment</th>
                            <th>Remarks</th>
                            <th>Encoded By</th>
                            <th>Location</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($expenses as $expense)
                        <tr>
                            <td>{{ $expense->name }}</td>
                            <td>{{ $expense->reference_number }}</td>
                            <td>{{ $expense->date }}</td>
                            <td>{{ number_format($expense->amount, 2) }}</td>
                            <td>
                                @if($expense->attachment)
                                    <button class="btn btn-sm btn-soft-primary" data-bs-toggle="modal" data-bs-target="#viewAttachment{{ $expense->id }}">View Attachment</button>
                                @endif
                            </td>
                            <td>{{ $expense->remarks }}</td>
                            
                            <td>{{ $expense->user->name }}</td>
                            <td>{{ $expense->location->name }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                    </div>
                </div>
    </div><!--end col-->
</div>
@foreach($expenses as $expense)
@include('expenses.edit')
@endforeach
@endsection
@section('js')
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
 <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
   <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
   <script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
   <script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>

   <script src="{{asset('inside_css/assets/js/pages/datatables.init.js')}}"></script>

{{-- <script src="{{asset('inside_css/assets/js/pages/datatables.init.js')}}"></script> --}}
<!-- App js -->
 <script src="{{asset('inside_css/assets/libs/prismjs/prism.js')}}"></script>
 <script>
         $('.example').DataTable({
            ordering: false,
            dom: 'Bfrtip',
            buttons: [
                'excel'
            ]
        });
 </script>
@endsection
