@extends('layouts.header')
@section('css')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css">
@endsection
@section('content')
<form  onsubmit="show();"   enctype="multipart/form-data">
    <div class='row mb-4'>
        <div class="col-md-2">
            <label class="form-label">Location</label>
            <select name="location" class="form-control" onchange="this.form.submit()">
                <option value="">Select Location</option>
                @foreach($locations as $key => $location)
                    <option value="{{ $location->id }}" @if($selectedLocation == $location->id) selected  @endif>
                        {{ $location->name }}
                    </option>
                @endforeach
            </select>
        </div>
        <div class="col-md-2">
            <label class="form-label">Date From</label>
            <input type='date' name='date_from' class='form-control' value='{{$date_from}}'   required>
        </div>
        <div class="col-md-2">
            <label class="form-label">Date To</label>
            <input type='date' name='date_to' class='form-control' value='{{$date_to}}' required>
        </div>
        <div class='col-xl-2'>
            <br>
                <button type="submit" class="btn btn-success" >
                <i class="ri-search-fill me-1"></i> Search
                </button>
        </div>
    </div>
</form>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Sales Report ({{date('M d, Y',strtotime($date_from))}} - {{date('M d, Y',strtotime($date_to))}})</h5>
                    </div>
                    <div class="card-body">
                        <button class="btn btn-primary mb-3" onclick="printTable()">Print Report</button>
                         <table id="salesReportTable" class=" table table-bordered " >
                            <thead>
                                <tr>
                                    <td colspan=4 class='text-center'>
                                       <img class="" src="{{asset('images/logo_mo.png')}}" width='400px' alt="Header Avatar">
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan=4 class='text-center'>
                                        Sales Report
                                    </td>
                                </tr>
                                 <tr>
                                    <td > Date: </td>
                                    <td>({{date('M d, Y',strtotime($date_from))}} - {{date('M d, Y',strtotime($date_to))}})</td>
                                    <td > Location: </td>
                                    <td>
                                        @php
                                            $sele = $locations->where('id',$selectedLocation)->first();
                                        @endphp
                                        @if($sele)
                                        {{$sele->name}}
                                    @endif
                                </td>
                                </tr>
                                <tr>
                                    <td > Generated by: </td>
                                    <td>{{auth()->user()->name}}</td>
                                    <td >  </td>
                                    <td>
                                        
                                </td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td > Sales</td>
                                    <td  class='text-success'>  <b>₱ {{number_format($transactions->where('product_id',null)->sum('amount_paid'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                                <tr>
                                    <td > Product</td>
                                    <td  class='text-success'>  <b>₱ {{number_format($transactions->where('product_id','!=',null)->sum('amount_paid'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                                <tr>
                                    <td > Total</td>
                                    <td  class='text-success'> <i> <b>₱ {{number_format($transactions->where('product_id','!=',null)->sum('amount_paid')+$transactions->where('product_id',null)->sum('amount_paid'),2)}}</b></i></td>
                                    <td colspan='2'></td>
                                </tr>
                               @php
                                    $totals = [
                                        'cash' => 0,
                                        'gcash' => 0,
                                        'HMO' => 0,
                                        'CC' => 0,
                                        'Debit' => 0,
                                        'Others' => 0,
                                    ];

                                    $transactions->flatMap(fn($t) => $t->payments)->each(function ($payment) use (&$totals) {
                                            $type = ($payment->payment_type);

                                            if (array_key_exists($type, $totals)) {
                                                $totals[$type] += $payment->amount;
                                            } 
                                        });
                                    @endphp

                                    @foreach($totals as $type => $amount)
                                        @if($amount != 0)
                                            @if($type != "cash")
                                            <tr>
                                                <td > {{ ucfirst($type) }}</td>
                                                <td class='text-danger'> <b>₱ {{ number_format($amount, 2) }}</b></td>
                                                <td colspan='2'></td>
                                            </tr>
                                            @endif
                                        @endif
                                    @endforeach

                                    @php
                                    $groupedExpenses = $expenses->groupBy('name');
                                @endphp
                                @php
                                    $totalExpenses = 0;
                                @endphp
                                @foreach($groupedExpenses as $name => $expensesByName)
                                    @php
                                        $groupedByPaymentType = $expensesByName->groupBy('payment_type');
                                    @endphp
                                
                                    @foreach($groupedByPaymentType as $paymentType => $group)
                                        @php
                                            $totalAmount = $group->sum('amount');
                                            $totalExpenses = $totalExpenses + $totalAmount;
                                            $class = $paymentType === 'cash' ? 'text-danger' : 'text-info';
                                        @endphp
                                        {{-- <tr>
                                            <td>{{ $name }}</td>
                                            <td class="{{ $class }}">
                                                <b>₱ {{ number_format($totalAmount, 2) }}</b>
                                                <small>({{ ucfirst($paymentType) }})</small>
                                            </td>
                                            <td colspan="2"></td>
                                        </tr> --}}
                                    @endforeach
                                @endforeach
                                <tr>
                                    <td >Total Expenses</td>
                                     <td class='text-danger'> <b>₱ {{number_format($totalExpenses,2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                                <tr>
                                    <td > Cash On Hand</td>
                                    <td > <b>₱ {{number_format($totals['cash']-$expenses->where('payment_type','cash')->sum('amount'),2)}}</b></td>
                                    <td colspan='2'></td>
                                </tr>
                            </tbody>
                         </table>
                         @if(auth()->user()->role == "Super Admin")
                         <table id="" class="example table table-bordered dt-responsive nowrap table-striped align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th colspan='12' class='text-center'><b>Overall Transactions</b></th>
                                </tr>
                                <tr>
                                    <th >#Id</th>
                                    <th >Client</th>
                                    <th >Dentist</th>
                                    <th >Dentist 2</th>
                                    <th >Dentist 3</th>
                                    <th>Payment</th>
                                    <th>Remarks</th>
                                    <th>Location</th>
                                    <th>Encoded by</th>
                                    <th >Treatment/Product</th>
                                    <th >Total Amount</th>
                                    <th >Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($transactions->sortByDesc('id') as $transaction)
                                <tr>
                                    <td>#{{$transaction->id}}</td>
                                    <td>{{$transaction->client->last_name}}, {{$transaction->client->first_name}}</td>
                                    <td>{{$transaction->dentist}}</td>
                                    <td>{{$transaction->dentist_2}}</td>
                                    <td>{{$transaction->dentist_3}}</td>
                                    <td>
                                        @php
                                            $totals = ['cash' => 0,'gcash' => 0,'HMO' => 0,'CC' => 0,'Debit' => 0,'Others' => 0];
                                        @endphp
                                        @foreach($transaction->payments as $payment)
                                            @php
                                                $type = $payment->payment_type;
                                                if(array_key_exists($type, $totals)) {
                                                    $totals[$type] += $payment->amount;
                                                }
                                            @endphp
                                        @endforeach
                                        @foreach($totals as $type => $amount)
                                            @if($amount != 0)
                                                <p>{{ ucfirst($type) }}: ₱{{ number_format($amount, 2) }}</p>
                                            @endif
                                        @endforeach
                                    </td>
                                    <td>{{$transaction->remarks}}</td>
                                    <td>{{$transaction->location->name}}</td>
                                    <td>{{$transaction->user->name}}</td>
                                    <td>
                                        @if($transaction->treatment)
                                            {{$transaction->treatment}} = {{number_format($transaction->amount_paid,2)}}
                                        @else
                                            {{$transaction->product->product_name}}({{$transaction->qty}}) = {{number_format($transaction->amount_paid,2)}}
                                        @endif
                                    </td>
                                    <td>{{number_format($transaction->amount_paid,2)}}</td>
                                    <td>
                                        <!-- Edit Button -->
                                        <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#editTransactionModal{{$transaction->id}}">
                                            <i class="fa fa-edit"></i> Edit
                                        </button>

                                        <!-- Delete Button -->
                                        <form action="{{ route('transactions.destroy', $transaction->id) }}" method="POST" style="display:inline;">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm"
                                                onclick="return confirm('Are you sure you want to delete this?')">
                                                <i class="fa fa-trash"></i> Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                               
                                @endforeach
                            </tbody>
                        </table>
                        @endif
                        <table id="" class="example table table-bordered dt-responsive nowrap table-striped align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th colspan='11' class='text-center'><b>Treatment</b></th>
                                </tr>
                                <tr>
                                    <th >#Id</th>
                                    <th >Client</th>
                                    <th >Dentist</th>
                                    <th >Dentist 2</th>
                                    <th >Dentist 3</th>
                                    <th>Payment</th>
                                    <th>Remarks</th>
                                    <th>Location</th>
                                    <th>Encoded by</th>
                                    <th >Treatment</th>
                                    <th >Total Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($transactions->sortByDesc('id')->where('product_id',null) as $transaction)
                                <tr>
                                    
                                    <td>#{{$transaction->id}}</td>
                                    <td>{{$transaction->client->last_name}}, {{$transaction->client->first_name}}</td>
                                    <td>{{$transaction->dentist}}</td>
                                    <td>{{$transaction->dentist_2}}</td>
                                    <td>{{$transaction->dentist_3}}</td>
                                    <td>
                                         @php
                                            $totals = [
                                                'cash' => 0,
                                                'gcash' => 0,
                                                'HMO' => 0,
                                                'CC' => 0,
                                                'Debit' => 0,
                                                'Others' => 0,
                                            ];
                                        @endphp
                                        @foreach($transaction->payments as $payment)
                                            @php
                                                $type = ($payment->payment_type);
                                                if(array_key_exists($type, $totals)) {
                                                    $totals[$type] += $payment->amount;
                                                }
                                            @endphp
                                        @endforeach
                                        @foreach($totals as $type => $amount)
                                            @if($amount != 0)
                                                <p>{{ ucfirst($type) }}: ₱{{ number_format($amount, 2) }}</p>
                                            @endif
                                        @endforeach

                                    </td>
                                    <td>{{$transaction->remarks}}</td>
                                    <td>{{$transaction->location->name}}</td>
                                    <td>{{$transaction->user->name}}</td>
                                    
                                    <td>{{$transaction->treatment}}</td>
                                    <td>{{number_format($transaction->amount_paid,2)}}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <table id="" class="example  table table-bordered dt-responsive nowrap table-striped align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th colspan='12' class='text-center'><b>Product</b></th>
                                </tr>
                                <tr>
                                    <th >#Id</th>
                                    <th >Client</th>
                                    <th >Dentist</th>
                                    <th >Dentist 2</th>
                                    <th >Dentist 3</th>
                                    <th>Payment</th>
                                    <th>Remarks</th>
                                    <th>Location</th>
                                    <th>Encoded by</th>
                                    
                                    <th >Product</th>
                                    <th >Qty</th>
                                    <th >Total Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                @foreach($transactions->sortByDesc('id')->where('product_id','!=',null) as $transaction)
                                <tr>
                                    
                                    <td>#{{$transaction->id}}</td>
                                    <td>{{$transaction->client->last_name}}, {{$transaction->client->first_name}}</td>
                                    <td>{{$transaction->dentist}}</td>
                                    <td>{{$transaction->dentist_2}}</td>
                                    <td>{{$transaction->dentist_3}}</td>
                                    <td>
                                          @foreach($transaction->payments as $payment)
                                            @php
                                                $type = ($payment->payment_type);
                                                if(array_key_exists($type, $totals)) {
                                                    $totals[$type] += $payment->amount;
                                                }
                                            @endphp
                                        @endforeach
                                        @foreach($totals as $type => $amount)
                                            @if($amount != 0)
                                                <p>{{ ucfirst($type) }}: ₱{{ number_format($amount, 2) }}</p>
                                            @endif
                                        @endforeach
                                    </td>
                                    <td>{{$transaction->remarks}}</td>
                                    <td>{{$transaction->location->name}}</td>
                                    <td>{{$transaction->user->name}}</td>
                                    
                                    <td>{{$transaction->product->product_name}}</td>
                                    <td>{{$transaction->qty}}</td>
                                    <td>{{number_format($transaction->amount_paid,2)}}</td>
                                </tr>
                                @endforeach
                                
                                
                            </tbody>
                        </table>
                          <table class="example table table-bordered dt-responsive nowrap table-striped align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th colspan=8 class='text-center'>Expenses</th>
                                </tr>
                                </tr>
                                <tr>
                                    <th>Expense Name</th>
                                    <th>Reference #</th>
                                    <th>Payment Type</th>
                                    <th>Date</th>
                                    <th>Amount</th>
                                    <th>Attachment</th>
                                    <th>Remarks</th>
                                    <th>Encoded By</th>
                                    <th>Location</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($expenses as $expense)
                                <tr>
                                    <td>{{ $expense->name }}</td>
                                    <td>{{ $expense->reference_number }}</td>
                                    <td>{{ $expense->payment_type }}</td>
                                    <td>{{ $expense->date }}</td>
                                    <td>{{ number_format($expense->amount, 2) }}</td>
                                    <td>
                                        @if($expense->attachment)
                                            <a href="{{ asset('uploads/expenses/' . $expense->attachment) }}" 
                                            target="_blank" 
                                            class="btn btn-sm btn-soft-primary">
                                            View Attachment
                                            </a>
                                        @endif
                                         @foreach($expense->attachments as $attachment)
                                            <a href="{{ asset('uploads/expenses/' . $attachment->attachment) }}" 
                                            target="_blank" 
                                            class="btn btn-sm btn-soft-primary d-block mb-1">
                                            {{ $attachment->file_name }}
                                            </a>
                                        @endforeach
                                    </td>
                                    <td>{{ $expense->remarks }}</td>
                                    
                                    <td>{{ $expense->user->name }}</td>
                                    <td>{{ $expense->location->name }}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
    </div><!--end col-->
</div>
@foreach($expenses as $expense)
@include('expenses.edit')
@endforeach
 @foreach($transactions->sortByDesc('id') as $transaction)
  <!-- Edit Modal -->
<div class="modal fade prod" id="editTransactionModal{{$transaction->id}}" tabindex="-1" aria-labelledby="editTransactionModalLabel{{$transaction->id}}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="{{ route('transactions.update', $transaction->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="modal-header">
                    <h5 class="modal-title" id="editTransactionModalLabel{{$transaction->id}}">Edit Transaction #{{$transaction->id}}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- Dentist -->
                    
                    <!-- Product or Service -->
                    @if($transaction->product)
                        <div class="mb-3">
                            <label for="product{{$transaction->id}}" class="form-label">Product</label>
                            <select name="product_id" class="form-select products" id="product{{$transaction->id}}">
                                @foreach($products as $product)
                                    <option value="{{$product->id}}" @if($transaction->product_id == $product->id) selected @endif>
                                        {{$product->product_name}}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="qty{{$transaction->id}}" class="form-label">Quantity</label>
                            <input type="number" name="qty" class="form-control" id="qty{{$transaction->id}}" value="{{$transaction->qty}}">
                        </div>
                    @elseif($transaction->treatment)
                        <div class="mb-3">
                            <label for="treatment{{$transaction->id}}" class="form-label">Service / Treatment</label>
                            <input type="text" name="treatment" class="form-control" id="treatment{{$transaction->id}}" value="{{$transaction->treatment}}">
                        </div>
                    @endif

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
 @endforeach
@endsection
@section('js')
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>

   <script src="{{asset('inside_css/assets/js/pages/datatables.init.js')}}"></script>

{{-- <script src="{{asset('inside_css/assets/js/pages/datatables.init.js')}}"></script> --}}
<!-- App js -->
 <script src="{{asset('inside_css/assets/libs/prismjs/prism.js')}}"></script>
 <script>
    $(document).ready(function() {
        $('.example').DataTable({
            ordering: false,
            dom: 'Bfrtip',
            buttons: [
                {
                    extend: 'print',
                    text: 'Print'
                },
                {
                    extend: 'excelHtml5',
                    text: 'Export to Excel'
                }
            ]
        });
    });
</script>
<script>
function printTable() {
    var table = document.getElementById("salesReportTable").outerHTML;
    var newWindow = window.open("", "", "width=900,height=650");
    newWindow.document.write(`
        <html>
            <head>
                <title>Sales Report</title>
                <style>
                    table {
                        width: 100%;
                        border-collapse: collapse;
                    }
                    table, th, td {
                        border: 1px solid black;
                        padding: 8px;
                    }
                </style>
            </head>
            <body>
                ${table}
            </body>
        </html>
    `);
    newWindow.document.close();
    newWindow.print();
}
</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script>
    // Use event delegation: initialize Select2 when modal is shown
    $('[id^=editTransactionModal]').on('shown.bs.modal', function () {
        // Find the select inside this modal only
        $(this).find('.products').select2({
            placeholder: "Search Product...",
            dropdownParent: $(this).find('.modal-content'), // important for modals
            width: '100%' // ensures it fits nicely
        });
    });

    // Optional: destroy Select2 when modal is hidden to avoid duplicates
    $('[id^=editTransactionModal]').on('hidden.bs.modal', function () {
        $(this).find('.products').select2('destroy');
    });
</script>
@endsection
